csr_req_distinguished_name_domain: ".ccsos.cnic.navy.mil"
csr_req_openssl_genrsa_keysize: "2048"
csr_req_distinguished_name_C: "US"
csr_req_distinguished_name_ST: "Virginia"
csr_req_distinguished_name_L: "Norfolk"
csr_req_distinguished_name_O: "U.S. Government"
csr_req_distinguished_name_OU1: "DoD"
csr_req_distinguished_name_OU2: "PKI"
csr_req_distinguished_name_OU3: "USN"
